# These are supported funding model platforms

github: douglasjunior
patreon: douglasjunior # Replace with a single Patreon username
open_collective: rn-keyboard-manager # Replace with a single Open Collective username
custom: paypal.me/douglasnassif
